version: "3.8"

services:
  backend:
    container_name: backend-prod-c
    build: ./backend
    image: backend-prod-i
    ports:
      - '3001:3001'

  frontend:
    container_name: frontend-prod-c
    image: frontend-prod-i
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'