name: Unit tests

on:
  pull_request:
    branches:
      - develop-frontend
      - develop-backend

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install (backend)
        run: npm ci
        working-directory: ./backend
      - name: Run tests (backend)
        run: npm test
        working-directory: ./backend